import React, { Component, Fragment } from "react";

export default class BurgeonSubPrivacyPolicy extends Component {
  render() {
    return (
      <Fragment>
        <div
          className="container-fluid py-3"
          style={{ height: "100vh", marginTop: "96px" }}
        >
          <div className="row">
            <div className="col-md-12 py-3">
              <h1 className="text-light text-center">Privacy Policy</h1>
              <hr></hr>
              <p>
                PT. Burgeon Adaire International ("we," "our," or "us") is
                committed to protecting your privacy. This Privacy Policy
                explains how your personal information is collected, used, and
                disclosed by PT. Burgeon Adaire International.
              </p>
              <p>
                This Privacy Policy applies to our website, and its associated
                subdomains (collectively, our "Service") alongside our
                application, PT. Burgeon Adaire International. By accessing or
                using our Service, you signify that you have read, understood,
                and agree to our collection, storage, use, and disclosure of
                your personal information as described in this Privacy Policy
                and our Terms of Service.
              </p>
              <h2 className="fw-light">Definitions and Key Terms</h2>
              <hr></hr>
              <p>
                To help explain things as clearly as possible in this Privacy
                Policy, every time any of these terms are referenced, are
                strictly defined as:
              </p>
              <ul>
                <li>
                  <strong>Cookie</strong>: small amount of data generated by a
                  website and saved by your web browser. It is used to identify
                  your browser, provide analytics, remember information about
                  you such as your language preference or login information.
                </li>
                <li>
                  <strong>Company</strong>: when this policy mentions "Company,"
                  "we," "us," or "our," it refers to PT. Burgeon Adaire
                  International, that is responsible for your information under
                  this Privacy Policy.
                </li>
                <li>
                  <strong>Country</strong>: where PT. Burgeon Adaire
                  International or the owners/founders of PT. Burgeon Adaire
                  International are based, in this case is Indonesia.
                </li>
                <li>
                  <strong>Customer</strong>: refers to the company, organization
                  or person that signs up to use the PT. Burgeon Adaire
                  International Service to manage the relationships with your
                  consumers or service users.
                </li>
                <li>
                  <strong>Device</strong>: any internet connected device such as
                  a phone, tablet, computer or any other device that can be used
                  to visit PT. Burgeon Adaire International and use the
                  services.
                </li>
                <li>
                  <strong>IP Address</strong>: every device connected to the
                  Internet is assigned a number known as an Internet protocol
                  (IP) address. These numbers are usually assigned in geographic
                  blocks. An IP address can often be used to identify the
                  location from which a device is connecting to the Internet.
                </li>
                <li>
                  <strong>Personnel</strong>: refers to those individuals who
                  are employed by PT. Burgeon Adaire International or are under
                  contract to perform a service on behalf of one of the parties.
                </li>
                <li>
                  <strong>Personal Data</strong>: any information that directly,
                  indirectly, or in connection with other information —
                  including a personal identification number — allows for the
                  identification or identifiability of a natural person.
                </li>
                <li>
                  <strong>Service</strong>: refers to the service provided by
                  PT. Burgeon Adaire International as described in the relative
                  terms (if available) and on this platform.
                </li>
                <li>
                  <strong>Third-party service</strong>: refers to advertisers,
                  contest sponsors, promotional and marketing partners, and
                  others who provide our content or whose products or services
                  we think may interest you.
                </li>
                <li>
                  <strong>Website</strong>: PT. Burgeon Adaire International's
                  site, which can be accessed via this URL:{" "}
                  <a
                    className="text-light text-decoration-none"
                    href="https://burgeonadaire.com"
                  >
                    https://burgeonadaire.com
                  </a>
                </li>
                <li>
                  <strong>You</strong>: a person or entity that is registered
                  with PT. Burgeon Adaire International to use the Services.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </Fragment>
    );
  }
}
